series:
  Kids_TV:
    - name: しまじろうのわお！
      url: https://tver.jp/series/sr2gk1r3w8
      subtitles: false

    - name: ガチャムク
      url: https://tver.jp/series/sr9azohyrb
      subtitles: false

    - name: ちびまる子ちゃん
      url: https://tver.jp/series/sr6z4bxpf7
      subtitles: false

    - name: それいけ！アンパンマン
      url: https://tver.jp/series/sruityj3v1
      subtitles: false

    - name: ドラえもん
      url: https://tver.jp/series/srtsxzl3si
      subtitles: false

  Variety_shows:
    - name: 世界の果てまでイッテQ！
      url: https://tver.jp/series/sr9gfdf2ex
      subtitles: false
      enabled: false

    - name: ホンマでっか！？TV
      url: https://tver.jp/series/srbcuxhq2k

  Documentary:
    - name: ザ・ノンフィクション
      url: https://tver.jp/series/sr7vfvos9u
      enabled: false

    - name: グッと！地球便
      url: https://tver.jp/series/srza176zgw
      enabled: false
    
    - name: 所さんの目がテン！
      url: https://tver.jp/series/srvjalspte

download_path: /mnt/media/Video
debug: false
subtitles_only: false
history:
  type: database
  db_connection_string: ${POSTGRESQL_CONNECTION}

yt_dlp_options:
  - -o
  - "%(series)s/%(title)s.%(ext)s"
  - --write-subs
