services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - SERVER_COUNTRIES=Japan
      - FIREWALL=on
    restart: unless-stopped

  tver-dl:
    # build: .
    image: ghcr.io/bry5an/tver-dl:latest
    pull_policy: always
    container_name: tver-dl
    depends_on:
      gluetun:
        condition: service_started
    network_mode: "service:gluetun"
    env_file:
      - .env
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - /mnt/media:/mnt/media
    restart: "no"
