services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - SERVER_COUNTRIES=Japan
      - FIREWALL=on
    restart: unless-stopped

  tver-dl:
    # build: .
    image: ghcr.io/bry5an/tver-dl:4835aac4ae27ef1f7649007b3248a2fafbe04764
    container_name: tver-dl
    depends_on:
      gluetun:
        condition: service_started
    network_mode: "service:gluetun"
    env_file:
      - .env
    environment:
      CONFIG_URL: https://raw.githubusercontent.com/bry5an/tver-dl/refs/heads/main/config.yaml
    restart: "no"
